clone:
  git:
    image: bash
    commands:
      - cd /home/0xmrtt
      - if [ -d Rosetta ]; then
      -   cd Rosetta
      -   git pull
      - else
      -   git clone https://git.exozy.me/Rosetta/Rosetta.git
      - fi

pipeline:
  build:
    image: fish
    secrets: [ access_token ]
    commands:
      - nix-env -iA nixpkgs.flatpak-builder
      - fish_add_path ~/.nix-profile/bin
      - flatpak-builder --repo=repo --force-clean build build-aux/flatpak/page.codeberg.Rosetta.Rosetta.json
      - flatpak build-bundle repo rosetta.flatpak page.codeberg.Rosetta.Rosetta
      - ls -la
      - curl --user $CI_REPO_OWNER:$ACCESS_TOKEN --upload-file rosetta.flatpak https://git.exozy.me/api/packages/$CI_REPO_OWNER/generic/$CI_REPO_NAME/$CI_BUILD_NUMBER/rosetta.flatpak
